export const ActionType = {
	SET_DATA_LOADING_STATUS: 'SET_DATA_LOADING_STATUS',
	SET_DATA: 'SET_DATA',
	SET_LOADING_ERROR: 'SET_LOADING_ERROR',
	SET_PAGES_COUNT: 'SET_PAGES_COUNT',
	SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
	SET_CURRENT_FILTER: 'SET_CURRENT_FILTER',
};
